<?php

    echo sdk_version() . "\n";
    $eight = "AwJPFwAA//+AH4APgA+AD4AHgAeAB4AHgAeAB4AHgAeAD4AfgB+AP+B///84ZAAAAAAAAAAAAAAZBOh+RQ4Cnh+VaD4tG2oeXKCHvj2mVL4JqGVeWjKKvleSGL9TlsQ/G55PPyugD38sqmm/N7zPny8lap0mpeZdR55FehCY5pZNHMZWTZ6Yljs1DLY6LURXPrQLFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";
    
    $six = "AwJkFQAA///////////AB8AHgAeAB4AHgA+AH4Af/B/8P/z//P////////80KAAAAAAAAAAAAAApF5zeUxsnXkmbpt4XnJxeNyKVnjQnKl5PJymeOa8qPkUUZT9jlmafPSpVPyKRH/Q9FyS8GaiZXBOpAVw3tKrcPDcUPCkQxdo1k+K7MJFfki8TnRcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";
    $six_plus = "AwJaLgAA//+Af4A/gA+AD4AHgAOAA4AHgAeAB4AHgAeAD+B/8P/w//////8sRDxMAAAAAAAAAAAshNPeKYiq/k2KAj4wECw+UhXFHh4YT94UGVAeW58HXhogzP4Ioo2+ECWMnhkqyJ4wN1deJMCX/jYNFF8XjhK/P5tE/yCmSN8tqMEfXy5IdxUzxh9VNYr/VCVI3EaqjzxYMUncR6BJHVKoSr0yMlc9OC7meiMx3romM8CbRaQMmDy9KNgknkw5PCIamTyr0xM7pBiWOyeaNzipl1dNLw0XPDgq1DSeBC9Ap+B1OjZVtT26U9UuocKSAAAAAAAAAAAAAAAAAAAAAA==";
    echo "same string      : " . matcher_Base64($six,$six) . "\n";
    echo "same print       : " . matcher_Base64($six,$six_plus) . "\n";
    echo "differnet prints : " . matcher_Base64($six,$eight) . "\n";
?>